name: ci
on: push

jobs:
 make-and-run:
  name: Compile and run
  runs-on: ubuntu-latest
  steps:
  
   - uses: actions/checkout@v2
   
   - name: make
     run: make all
     
   - name: run
     run: make run